CREATE TABLE produto(
id INT PRIMARY KEY AUTO_INCREMENT,
ativo BOOLEAN NOT NULL DEFAULT TRUE,
sku VARCHAR(50) unique,
nome VARCHAR(50) NOT NULL,
descrição VARCHAR(100),
valor_unitario DECIMAL(19,2) NOT NULL DEFAULT 0.00
);

DESC produto;

DROP TABLE cliente;

CREATE TABLE cliente(
id INT PRIMARY KEY AUTO_INCREMENT,
ativo BOOLEAN NOT NULL DEFAULT TRUE,
nome VARCHAR(50) NOT NULL,
cpf VARCHAR(50) NOT NULL unique
);

CREATE TABLE venda(
id INT PRIMARY KEY AUTO_INCREMENT,
data_venda DATETIME NOT NULL,
cliente_id INT NOT NULL,
status VARCHAR(1) NOT NULL DEFAULT 'P',
quantidade DECIMAL(19,2) NOT NULL,
valor_total DECIMAL(19,2) NOT NULL,
FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);

